// Generated by gencpp from file qt_connection/AbRatioRequest.msg
// DO NOT EDIT!


#ifndef QT_CONNECTION_MESSAGE_ABRATIOREQUEST_H
#define QT_CONNECTION_MESSAGE_ABRATIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qt_connection
{
template <class ContainerAllocator>
struct AbRatioRequest_
{
  typedef AbRatioRequest_<ContainerAllocator> Type;

  AbRatioRequest_()
    : ratio_req(0.0)  {
    }
  AbRatioRequest_(const ContainerAllocator& _alloc)
    : ratio_req(0.0)  {
  (void)_alloc;
    }



   typedef double _ratio_req_type;
  _ratio_req_type ratio_req;





  typedef boost::shared_ptr< ::qt_connection::AbRatioRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_connection::AbRatioRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AbRatioRequest_

typedef ::qt_connection::AbRatioRequest_<std::allocator<void> > AbRatioRequest;

typedef boost::shared_ptr< ::qt_connection::AbRatioRequest > AbRatioRequestPtr;
typedef boost::shared_ptr< ::qt_connection::AbRatioRequest const> AbRatioRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_connection::AbRatioRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_connection::AbRatioRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qt_connection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qt_connection::AbRatioRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_connection::AbRatioRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_connection::AbRatioRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_connection::AbRatioRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_connection::AbRatioRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_connection::AbRatioRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_connection::AbRatioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6371066b87b865d209aa230ed733dffc";
  }

  static const char* value(const ::qt_connection::AbRatioRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6371066b87b865d2ULL;
  static const uint64_t static_value2 = 0x09aa230ed733dffcULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_connection::AbRatioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_connection/AbRatioRequest";
  }

  static const char* value(const ::qt_connection::AbRatioRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_connection::AbRatioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 ratio_req\n\
";
  }

  static const char* value(const ::qt_connection::AbRatioRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_connection::AbRatioRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ratio_req);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AbRatioRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_connection::AbRatioRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_connection::AbRatioRequest_<ContainerAllocator>& v)
  {
    s << indent << "ratio_req: ";
    Printer<double>::stream(s, indent + "  ", v.ratio_req);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_CONNECTION_MESSAGE_ABRATIOREQUEST_H
