// Generated by gencpp from file qt_connection/ColorRequest.msg
// DO NOT EDIT!


#ifndef QT_CONNECTION_MESSAGE_COLORREQUEST_H
#define QT_CONNECTION_MESSAGE_COLORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qt_connection
{
template <class ContainerAllocator>
struct ColorRequest_
{
  typedef ColorRequest_<ContainerAllocator> Type;

  ColorRequest_()
    : color_req()  {
    }
  ColorRequest_(const ContainerAllocator& _alloc)
    : color_req(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _color_req_type;
  _color_req_type color_req;





  typedef boost::shared_ptr< ::qt_connection::ColorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_connection::ColorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ColorRequest_

typedef ::qt_connection::ColorRequest_<std::allocator<void> > ColorRequest;

typedef boost::shared_ptr< ::qt_connection::ColorRequest > ColorRequestPtr;
typedef boost::shared_ptr< ::qt_connection::ColorRequest const> ColorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_connection::ColorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_connection::ColorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qt_connection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qt_connection::ColorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_connection::ColorRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_connection::ColorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_connection::ColorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_connection::ColorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_connection::ColorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_connection::ColorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d72079bb2595441aea2407dc5c59d06c";
  }

  static const char* value(const ::qt_connection::ColorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd72079bb2595441aULL;
  static const uint64_t static_value2 = 0xea2407dc5c59d06cULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_connection::ColorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_connection/ColorRequest";
  }

  static const char* value(const ::qt_connection::ColorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_connection::ColorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string color_req\n\
";
  }

  static const char* value(const ::qt_connection::ColorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_connection::ColorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color_req);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_connection::ColorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_connection::ColorRequest_<ContainerAllocator>& v)
  {
    s << indent << "color_req: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.color_req);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_CONNECTION_MESSAGE_COLORREQUEST_H
