// Generated by gencpp from file qt_connection/ReadyResponse.msg
// DO NOT EDIT!


#ifndef QT_CONNECTION_MESSAGE_READYRESPONSE_H
#define QT_CONNECTION_MESSAGE_READYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qt_connection
{
template <class ContainerAllocator>
struct ReadyResponse_
{
  typedef ReadyResponse_<ContainerAllocator> Type;

  ReadyResponse_()
    : finish(false)  {
    }
  ReadyResponse_(const ContainerAllocator& _alloc)
    : finish(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finish_type;
  _finish_type finish;





  typedef boost::shared_ptr< ::qt_connection::ReadyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_connection::ReadyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReadyResponse_

typedef ::qt_connection::ReadyResponse_<std::allocator<void> > ReadyResponse;

typedef boost::shared_ptr< ::qt_connection::ReadyResponse > ReadyResponsePtr;
typedef boost::shared_ptr< ::qt_connection::ReadyResponse const> ReadyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_connection::ReadyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_connection::ReadyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qt_connection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qt_connection::ReadyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_connection::ReadyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_connection::ReadyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_connection::ReadyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_connection::ReadyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_connection::ReadyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_connection::ReadyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "474a58dbb494a45bb1ca99544cd64e45";
  }

  static const char* value(const ::qt_connection::ReadyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x474a58dbb494a45bULL;
  static const uint64_t static_value2 = 0xb1ca99544cd64e45ULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_connection::ReadyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_connection/ReadyResponse";
  }

  static const char* value(const ::qt_connection::ReadyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_connection::ReadyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool finish\n\
";
  }

  static const char* value(const ::qt_connection::ReadyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_connection::ReadyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finish);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_connection::ReadyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_connection::ReadyResponse_<ContainerAllocator>& v)
  {
    s << indent << "finish: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finish);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_CONNECTION_MESSAGE_READYRESPONSE_H
