// Generated by gencpp from file test_srv/test_srvResponse.msg
// DO NOT EDIT!


#ifndef TEST_SRV_MESSAGE_TEST_SRVRESPONSE_H
#define TEST_SRV_MESSAGE_TEST_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_srv
{
template <class ContainerAllocator>
struct test_srvResponse_
{
  typedef test_srvResponse_<ContainerAllocator> Type;

  test_srvResponse_()
    : output(0)  {
    }
  test_srvResponse_(const ContainerAllocator& _alloc)
    : output(0)  {
  (void)_alloc;
    }



   typedef int64_t _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::test_srv::test_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_srv::test_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct test_srvResponse_

typedef ::test_srv::test_srvResponse_<std::allocator<void> > test_srvResponse;

typedef boost::shared_ptr< ::test_srv::test_srvResponse > test_srvResponsePtr;
typedef boost::shared_ptr< ::test_srv::test_srvResponse const> test_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_srv::test_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_srv::test_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_srv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_srv::test_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_srv::test_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_srv::test_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_srv::test_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_srv::test_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_srv::test_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_srv::test_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eaf29e6e649dbd18239f4c3f12579de7";
  }

  static const char* value(const ::test_srv::test_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeaf29e6e649dbd18ULL;
  static const uint64_t static_value2 = 0x239f4c3f12579de7ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_srv::test_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_srv/test_srvResponse";
  }

  static const char* value(const ::test_srv::test_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_srv::test_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int64       output\n\
";
  }

  static const char* value(const ::test_srv::test_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_srv::test_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct test_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_srv::test_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_srv::test_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<int64_t>::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_SRV_MESSAGE_TEST_SRVRESPONSE_H
