// Generated by gencpp from file test_srv/test_srvRequest.msg
// DO NOT EDIT!


#ifndef TEST_SRV_MESSAGE_TEST_SRVREQUEST_H
#define TEST_SRV_MESSAGE_TEST_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_srv
{
template <class ContainerAllocator>
struct test_srvRequest_
{
  typedef test_srvRequest_<ContainerAllocator> Type;

  test_srvRequest_()
    : input(0)  {
    }
  test_srvRequest_(const ContainerAllocator& _alloc)
    : input(0)  {
  (void)_alloc;
    }



   typedef int64_t _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::test_srv::test_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_srv::test_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct test_srvRequest_

typedef ::test_srv::test_srvRequest_<std::allocator<void> > test_srvRequest;

typedef boost::shared_ptr< ::test_srv::test_srvRequest > test_srvRequestPtr;
typedef boost::shared_ptr< ::test_srv::test_srvRequest const> test_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_srv::test_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_srv::test_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_srv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_srv::test_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_srv::test_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_srv::test_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_srv::test_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_srv::test_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_srv::test_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_srv::test_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efb1911a9ea9163151d70e4586fa0801";
  }

  static const char* value(const ::test_srv::test_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefb1911a9ea91631ULL;
  static const uint64_t static_value2 = 0x51d70e4586fa0801ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_srv::test_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_srv/test_srvRequest";
  }

  static const char* value(const ::test_srv::test_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_srv::test_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int64       input\n\
";
  }

  static const char* value(const ::test_srv::test_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_srv::test_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct test_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_srv::test_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_srv::test_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<int64_t>::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_SRV_MESSAGE_TEST_SRVREQUEST_H
