// Generated by gencpp from file move_control/DesiredPoseRequest.msg
// DO NOT EDIT!


#ifndef MOVE_CONTROL_MESSAGE_DESIREDPOSEREQUEST_H
#define MOVE_CONTROL_MESSAGE_DESIREDPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_control
{
template <class ContainerAllocator>
struct DesiredPoseRequest_
{
  typedef DesiredPoseRequest_<ContainerAllocator> Type;

  DesiredPoseRequest_()
    : x_d(0.0)
    , y_d(0.0)
    , theta_d(0.0)  {
    }
  DesiredPoseRequest_(const ContainerAllocator& _alloc)
    : x_d(0.0)
    , y_d(0.0)
    , theta_d(0.0)  {
  (void)_alloc;
    }



   typedef double _x_d_type;
  _x_d_type x_d;

   typedef double _y_d_type;
  _y_d_type y_d;

   typedef double _theta_d_type;
  _theta_d_type theta_d;





  typedef boost::shared_ptr< ::move_control::DesiredPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_control::DesiredPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DesiredPoseRequest_

typedef ::move_control::DesiredPoseRequest_<std::allocator<void> > DesiredPoseRequest;

typedef boost::shared_ptr< ::move_control::DesiredPoseRequest > DesiredPoseRequestPtr;
typedef boost::shared_ptr< ::move_control::DesiredPoseRequest const> DesiredPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_control::DesiredPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_control::DesiredPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace move_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::move_control::DesiredPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_control::DesiredPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_control::DesiredPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_control::DesiredPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_control::DesiredPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_control::DesiredPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_control::DesiredPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "93023edf62509f0c837bd28a9edfe755";
  }

  static const char* value(const ::move_control::DesiredPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x93023edf62509f0cULL;
  static const uint64_t static_value2 = 0x837bd28a9edfe755ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_control::DesiredPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_control/DesiredPoseRequest";
  }

  static const char* value(const ::move_control::DesiredPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_control::DesiredPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x_d\n\
float64 y_d\n\
float64 theta_d\n\
";
  }

  static const char* value(const ::move_control::DesiredPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_control::DesiredPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_d);
      stream.next(m.y_d);
      stream.next(m.theta_d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DesiredPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_control::DesiredPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_control::DesiredPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "x_d: ";
    Printer<double>::stream(s, indent + "  ", v.x_d);
    s << indent << "y_d: ";
    Printer<double>::stream(s, indent + "  ", v.y_d);
    s << indent << "theta_d: ";
    Printer<double>::stream(s, indent + "  ", v.theta_d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_CONTROL_MESSAGE_DESIREDPOSEREQUEST_H
