// Generated by gencpp from file move_control/DesiredPoseResponse.msg
// DO NOT EDIT!


#ifndef MOVE_CONTROL_MESSAGE_DESIREDPOSERESPONSE_H
#define MOVE_CONTROL_MESSAGE_DESIREDPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_control
{
template <class ContainerAllocator>
struct DesiredPoseResponse_
{
  typedef DesiredPoseResponse_<ContainerAllocator> Type;

  DesiredPoseResponse_()
    : finish(false)  {
    }
  DesiredPoseResponse_(const ContainerAllocator& _alloc)
    : finish(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finish_type;
  _finish_type finish;





  typedef boost::shared_ptr< ::move_control::DesiredPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_control::DesiredPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DesiredPoseResponse_

typedef ::move_control::DesiredPoseResponse_<std::allocator<void> > DesiredPoseResponse;

typedef boost::shared_ptr< ::move_control::DesiredPoseResponse > DesiredPoseResponsePtr;
typedef boost::shared_ptr< ::move_control::DesiredPoseResponse const> DesiredPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_control::DesiredPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_control::DesiredPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace move_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::move_control::DesiredPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_control::DesiredPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_control::DesiredPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_control::DesiredPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_control::DesiredPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_control::DesiredPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_control::DesiredPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "474a58dbb494a45bb1ca99544cd64e45";
  }

  static const char* value(const ::move_control::DesiredPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x474a58dbb494a45bULL;
  static const uint64_t static_value2 = 0xb1ca99544cd64e45ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_control::DesiredPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_control/DesiredPoseResponse";
  }

  static const char* value(const ::move_control::DesiredPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_control::DesiredPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool finish\n\
\n\
";
  }

  static const char* value(const ::move_control::DesiredPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_control::DesiredPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finish);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DesiredPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_control::DesiredPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_control::DesiredPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "finish: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finish);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_CONTROL_MESSAGE_DESIREDPOSERESPONSE_H
