// Generated by gencpp from file move_control/ImgPoint.msg
// DO NOT EDIT!


#ifndef MOVE_CONTROL_MESSAGE_IMGPOINT_H
#define MOVE_CONTROL_MESSAGE_IMGPOINT_H

#include <ros/service_traits.h>


#include <move_control/ImgPointRequest.h>
#include <move_control/ImgPointResponse.h>


namespace move_control
{

struct ImgPoint
{

typedef ImgPointRequest Request;
typedef ImgPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImgPoint
} // namespace move_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_control::ImgPoint > {
  static const char* value()
  {
    return "474a58dbb494a45bb1ca99544cd64e45";
  }

  static const char* value(const ::move_control::ImgPoint&) { return value(); }
};

template<>
struct DataType< ::move_control::ImgPoint > {
  static const char* value()
  {
    return "move_control/ImgPoint";
  }

  static const char* value(const ::move_control::ImgPoint&) { return value(); }
};


// service_traits::MD5Sum< ::move_control::ImgPointRequest> should match 
// service_traits::MD5Sum< ::move_control::ImgPoint > 
template<>
struct MD5Sum< ::move_control::ImgPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_control::ImgPoint >::value();
  }
  static const char* value(const ::move_control::ImgPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_control::ImgPointRequest> should match 
// service_traits::DataType< ::move_control::ImgPoint > 
template<>
struct DataType< ::move_control::ImgPointRequest>
{
  static const char* value()
  {
    return DataType< ::move_control::ImgPoint >::value();
  }
  static const char* value(const ::move_control::ImgPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_control::ImgPointResponse> should match 
// service_traits::MD5Sum< ::move_control::ImgPoint > 
template<>
struct MD5Sum< ::move_control::ImgPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_control::ImgPoint >::value();
  }
  static const char* value(const ::move_control::ImgPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_control::ImgPointResponse> should match 
// service_traits::DataType< ::move_control::ImgPoint > 
template<>
struct DataType< ::move_control::ImgPointResponse>
{
  static const char* value()
  {
    return DataType< ::move_control::ImgPoint >::value();
  }
  static const char* value(const ::move_control::ImgPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_CONTROL_MESSAGE_IMGPOINT_H
