// Generated by gencpp from file test_1/test_srvRequest.msg
// DO NOT EDIT!


#ifndef TEST_1_MESSAGE_TEST_SRVREQUEST_H
#define TEST_1_MESSAGE_TEST_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace test_1
{
template <class ContainerAllocator>
struct test_srvRequest_
{
  typedef test_srvRequest_<ContainerAllocator> Type;

  test_srvRequest_()
    : input_text()
    , input(0)  {
    }
  test_srvRequest_(const ContainerAllocator& _alloc)
    : input_text(_alloc)
    , input(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _input_text_type;
  _input_text_type input_text;

   typedef int64_t _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::test_1::test_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_1::test_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct test_srvRequest_

typedef ::test_1::test_srvRequest_<std::allocator<void> > test_srvRequest;

typedef boost::shared_ptr< ::test_1::test_srvRequest > test_srvRequestPtr;
typedef boost::shared_ptr< ::test_1::test_srvRequest const> test_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_1::test_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_1::test_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_1::test_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_1::test_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_1::test_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_1::test_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_1::test_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_1::test_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_1::test_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d038a94240ddf47bff3002f74ee7ec8b";
  }

  static const char* value(const ::test_1::test_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd038a94240ddf47bULL;
  static const uint64_t static_value2 = 0xff3002f74ee7ec8bULL;
};

template<class ContainerAllocator>
struct DataType< ::test_1::test_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_1/test_srvRequest";
  }

  static const char* value(const ::test_1::test_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_1::test_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String input_text\n\
int64       input\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::test_1::test_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_1::test_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input_text);
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct test_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_1::test_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_1::test_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "input_text: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.input_text);
    s << indent << "input: ";
    Printer<int64_t>::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_1_MESSAGE_TEST_SRVREQUEST_H
