// Generated by gencpp from file test_1/test_srv.msg
// DO NOT EDIT!


#ifndef TEST_1_MESSAGE_TEST_SRV_H
#define TEST_1_MESSAGE_TEST_SRV_H

#include <ros/service_traits.h>


#include <test_1/test_srvRequest.h>
#include <test_1/test_srvResponse.h>


namespace test_1
{

struct test_srv
{

typedef test_srvRequest Request;
typedef test_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct test_srv
} // namespace test_1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_1::test_srv > {
  static const char* value()
  {
    return "53244230a18aeabb17bd81ddb3a8f9e8";
  }

  static const char* value(const ::test_1::test_srv&) { return value(); }
};

template<>
struct DataType< ::test_1::test_srv > {
  static const char* value()
  {
    return "test_1/test_srv";
  }

  static const char* value(const ::test_1::test_srv&) { return value(); }
};


// service_traits::MD5Sum< ::test_1::test_srvRequest> should match 
// service_traits::MD5Sum< ::test_1::test_srv > 
template<>
struct MD5Sum< ::test_1::test_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_1::test_srv >::value();
  }
  static const char* value(const ::test_1::test_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_1::test_srvRequest> should match 
// service_traits::DataType< ::test_1::test_srv > 
template<>
struct DataType< ::test_1::test_srvRequest>
{
  static const char* value()
  {
    return DataType< ::test_1::test_srv >::value();
  }
  static const char* value(const ::test_1::test_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_1::test_srvResponse> should match 
// service_traits::MD5Sum< ::test_1::test_srv > 
template<>
struct MD5Sum< ::test_1::test_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_1::test_srv >::value();
  }
  static const char* value(const ::test_1::test_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_1::test_srvResponse> should match 
// service_traits::DataType< ::test_1::test_srv > 
template<>
struct DataType< ::test_1::test_srvResponse>
{
  static const char* value()
  {
    return DataType< ::test_1::test_srv >::value();
  }
  static const char* value(const ::test_1::test_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_1_MESSAGE_TEST_SRV_H
