// Generated by gencpp from file simple_move/simple_moveResult.msg
// DO NOT EDIT!


#ifndef SIMPLE_MOVE_MESSAGE_SIMPLE_MOVERESULT_H
#define SIMPLE_MOVE_MESSAGE_SIMPLE_MOVERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace simple_move
{
template <class ContainerAllocator>
struct simple_moveResult_
{
  typedef simple_moveResult_<ContainerAllocator> Type;

  simple_moveResult_()
    : final_pose()  {
    }
  simple_moveResult_(const ContainerAllocator& _alloc)
    : final_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _final_pose_type;
  _final_pose_type final_pose;





  typedef boost::shared_ptr< ::simple_move::simple_moveResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_move::simple_moveResult_<ContainerAllocator> const> ConstPtr;

}; // struct simple_moveResult_

typedef ::simple_move::simple_moveResult_<std::allocator<void> > simple_moveResult;

typedef boost::shared_ptr< ::simple_move::simple_moveResult > simple_moveResultPtr;
typedef boost::shared_ptr< ::simple_move::simple_moveResult const> simple_moveResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_move::simple_moveResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_move::simple_moveResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simple_move

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'simple_move': ['/home/phw/catkin_ws/devel/share/simple_move/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simple_move::simple_moveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_move::simple_moveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_move::simple_moveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_move::simple_moveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_move::simple_moveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_move::simple_moveResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_move::simple_moveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b03b05e2f5c62e96e4cec4715bf432f";
  }

  static const char* value(const ::simple_move::simple_moveResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b03b05e2f5c62e9ULL;
  static const uint64_t static_value2 = 0x6e4cec4715bf432fULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_move::simple_moveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_move/simple_moveResult";
  }

  static const char* value(const ::simple_move::simple_moveResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_move::simple_moveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
geometry_msgs/Pose2D final_pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::simple_move::simple_moveResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_move::simple_moveResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simple_moveResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_move::simple_moveResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_move::simple_moveResult_<ContainerAllocator>& v)
  {
    s << indent << "final_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.final_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_MOVE_MESSAGE_SIMPLE_MOVERESULT_H
