// Generated by gencpp from file simple_move/simple_move_serverRequest.msg
// DO NOT EDIT!


#ifndef SIMPLE_MOVE_MESSAGE_SIMPLE_MOVE_SERVERREQUEST_H
#define SIMPLE_MOVE_MESSAGE_SIMPLE_MOVE_SERVERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_move
{
template <class ContainerAllocator>
struct simple_move_serverRequest_
{
  typedef simple_move_serverRequest_<ContainerAllocator> Type;

  simple_move_serverRequest_()
    : Execute(false)  {
    }
  simple_move_serverRequest_(const ContainerAllocator& _alloc)
    : Execute(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Execute_type;
  _Execute_type Execute;





  typedef boost::shared_ptr< ::simple_move::simple_move_serverRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_move::simple_move_serverRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simple_move_serverRequest_

typedef ::simple_move::simple_move_serverRequest_<std::allocator<void> > simple_move_serverRequest;

typedef boost::shared_ptr< ::simple_move::simple_move_serverRequest > simple_move_serverRequestPtr;
typedef boost::shared_ptr< ::simple_move::simple_move_serverRequest const> simple_move_serverRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_move::simple_move_serverRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_move::simple_move_serverRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simple_move

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'simple_move': ['/home/phw/catkin_ws/devel/share/simple_move/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simple_move::simple_move_serverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_move::simple_move_serverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_move::simple_move_serverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_move::simple_move_serverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_move::simple_move_serverRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_move::simple_move_serverRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_move::simple_move_serverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa4d8c189352d1ea690d00f17f0a28b5";
  }

  static const char* value(const ::simple_move::simple_move_serverRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa4d8c189352d1eaULL;
  static const uint64_t static_value2 = 0x690d00f17f0a28b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_move::simple_move_serverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_move/simple_move_serverRequest";
  }

  static const char* value(const ::simple_move::simple_move_serverRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_move::simple_move_serverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool  Execute\n\
";
  }

  static const char* value(const ::simple_move::simple_move_serverRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_move::simple_move_serverRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Execute);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simple_move_serverRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_move::simple_move_serverRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_move::simple_move_serverRequest_<ContainerAllocator>& v)
  {
    s << indent << "Execute: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Execute);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_MOVE_MESSAGE_SIMPLE_MOVE_SERVERREQUEST_H
