// Generated by gencpp from file img_prc/Dominant.msg
// DO NOT EDIT!


#ifndef IMG_PRC_MESSAGE_DOMINANT_H
#define IMG_PRC_MESSAGE_DOMINANT_H

#include <ros/service_traits.h>


#include <img_prc/DominantRequest.h>
#include <img_prc/DominantResponse.h>


namespace img_prc
{

struct Dominant
{

typedef DominantRequest Request;
typedef DominantResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Dominant
} // namespace img_prc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::img_prc::Dominant > {
  static const char* value()
  {
    return "822675abf3202697f33f9cb1bce7557d";
  }

  static const char* value(const ::img_prc::Dominant&) { return value(); }
};

template<>
struct DataType< ::img_prc::Dominant > {
  static const char* value()
  {
    return "img_prc/Dominant";
  }

  static const char* value(const ::img_prc::Dominant&) { return value(); }
};


// service_traits::MD5Sum< ::img_prc::DominantRequest> should match 
// service_traits::MD5Sum< ::img_prc::Dominant > 
template<>
struct MD5Sum< ::img_prc::DominantRequest>
{
  static const char* value()
  {
    return MD5Sum< ::img_prc::Dominant >::value();
  }
  static const char* value(const ::img_prc::DominantRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::img_prc::DominantRequest> should match 
// service_traits::DataType< ::img_prc::Dominant > 
template<>
struct DataType< ::img_prc::DominantRequest>
{
  static const char* value()
  {
    return DataType< ::img_prc::Dominant >::value();
  }
  static const char* value(const ::img_prc::DominantRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::img_prc::DominantResponse> should match 
// service_traits::MD5Sum< ::img_prc::Dominant > 
template<>
struct MD5Sum< ::img_prc::DominantResponse>
{
  static const char* value()
  {
    return MD5Sum< ::img_prc::Dominant >::value();
  }
  static const char* value(const ::img_prc::DominantResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::img_prc::DominantResponse> should match 
// service_traits::DataType< ::img_prc::Dominant > 
template<>
struct DataType< ::img_prc::DominantResponse>
{
  static const char* value()
  {
    return DataType< ::img_prc::Dominant >::value();
  }
  static const char* value(const ::img_prc::DominantResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMG_PRC_MESSAGE_DOMINANT_H
