// Generated by gencpp from file img_prc/Graubild.msg
// DO NOT EDIT!


#ifndef IMG_PRC_MESSAGE_GRAUBILD_H
#define IMG_PRC_MESSAGE_GRAUBILD_H

#include <ros/service_traits.h>


#include <img_prc/GraubildRequest.h>
#include <img_prc/GraubildResponse.h>


namespace img_prc
{

struct Graubild
{

typedef GraubildRequest Request;
typedef GraubildResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Graubild
} // namespace img_prc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::img_prc::Graubild > {
  static const char* value()
  {
    return "eb47099b9f958df018aedaea11c200fb";
  }

  static const char* value(const ::img_prc::Graubild&) { return value(); }
};

template<>
struct DataType< ::img_prc::Graubild > {
  static const char* value()
  {
    return "img_prc/Graubild";
  }

  static const char* value(const ::img_prc::Graubild&) { return value(); }
};


// service_traits::MD5Sum< ::img_prc::GraubildRequest> should match 
// service_traits::MD5Sum< ::img_prc::Graubild > 
template<>
struct MD5Sum< ::img_prc::GraubildRequest>
{
  static const char* value()
  {
    return MD5Sum< ::img_prc::Graubild >::value();
  }
  static const char* value(const ::img_prc::GraubildRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::img_prc::GraubildRequest> should match 
// service_traits::DataType< ::img_prc::Graubild > 
template<>
struct DataType< ::img_prc::GraubildRequest>
{
  static const char* value()
  {
    return DataType< ::img_prc::Graubild >::value();
  }
  static const char* value(const ::img_prc::GraubildRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::img_prc::GraubildResponse> should match 
// service_traits::MD5Sum< ::img_prc::Graubild > 
template<>
struct MD5Sum< ::img_prc::GraubildResponse>
{
  static const char* value()
  {
    return MD5Sum< ::img_prc::Graubild >::value();
  }
  static const char* value(const ::img_prc::GraubildResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::img_prc::GraubildResponse> should match 
// service_traits::DataType< ::img_prc::Graubild > 
template<>
struct DataType< ::img_prc::GraubildResponse>
{
  static const char* value()
  {
    return DataType< ::img_prc::Graubild >::value();
  }
  static const char* value(const ::img_prc::GraubildResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMG_PRC_MESSAGE_GRAUBILD_H
