(cl:defpackage img_prc-srv
  (:use )
  (:export
   "DOMINANT"
   "<DOMINANT-REQUEST>"
   "DOMINANT-REQUEST"
   "<DOMINANT-RESPONSE>"
   "DOMINANT-RESPONSE"
   "GRAUBILD"
   "<GRAUBILD-REQUEST>"
   "GRAUBILD-REQUEST"
   "<GRAUBILD-RESPONSE>"
   "GRAUBILD-RESPONSE"
   "KANTEN"
   "<KANTEN-REQUEST>"
   "KANTEN-REQUEST"
   "<KANTEN-RESPONSE>"
   "KANTEN-RESPONSE"
   "NEGBILD"
   "<NEGBILD-REQUEST>"
   "NEGBILD-REQUEST"
   "<NEGBILD-RESPONSE>"
   "NEGBILD-RESPONSE"
  ))

