// Generated by gencpp from file create_map/create_map_srvRequest.msg
// DO NOT EDIT!


#ifndef CREATE_MAP_MESSAGE_CREATE_MAP_SRVREQUEST_H
#define CREATE_MAP_MESSAGE_CREATE_MAP_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace create_map
{
template <class ContainerAllocator>
struct create_map_srvRequest_
{
  typedef create_map_srvRequest_<ContainerAllocator> Type;

  create_map_srvRequest_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , a(0.0)
    , b(0.0)
    , teamcolor(false)  {
    }
  create_map_srvRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , a(0.0)
    , b(0.0)
    , teamcolor(false)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;

   typedef float _a_type;
  _a_type a;

   typedef float _b_type;
  _b_type b;

   typedef uint8_t _teamcolor_type;
  _teamcolor_type teamcolor;





  typedef boost::shared_ptr< ::create_map::create_map_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::create_map::create_map_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct create_map_srvRequest_

typedef ::create_map::create_map_srvRequest_<std::allocator<void> > create_map_srvRequest;

typedef boost::shared_ptr< ::create_map::create_map_srvRequest > create_map_srvRequestPtr;
typedef boost::shared_ptr< ::create_map::create_map_srvRequest const> create_map_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::create_map::create_map_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::create_map::create_map_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace create_map

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::create_map::create_map_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::create_map::create_map_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::create_map::create_map_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::create_map::create_map_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create_map::create_map_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create_map::create_map_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::create_map::create_map_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce11d8a36ed22138f3ccd3ee60b5ca4a";
  }

  static const char* value(const ::create_map::create_map_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce11d8a36ed22138ULL;
  static const uint64_t static_value2 = 0xf3ccd3ee60b5ca4aULL;
};

template<class ContainerAllocator>
struct DataType< ::create_map::create_map_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "create_map/create_map_srvRequest";
  }

  static const char* value(const ::create_map::create_map_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::create_map::create_map_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32                x\n\
float32                y\n\
float32                theta\n\
float32                a\n\
float32                b\n\
bool                   teamcolor\n\
";
  }

  static const char* value(const ::create_map::create_map_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::create_map::create_map_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.teamcolor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct create_map_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::create_map::create_map_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::create_map::create_map_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<float>::stream(s, indent + "  ", v.b);
    s << indent << "teamcolor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.teamcolor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CREATE_MAP_MESSAGE_CREATE_MAP_SRVREQUEST_H
