// Generated by gencpp from file create_map/create_map_srv.msg
// DO NOT EDIT!


#ifndef CREATE_MAP_MESSAGE_CREATE_MAP_SRV_H
#define CREATE_MAP_MESSAGE_CREATE_MAP_SRV_H

#include <ros/service_traits.h>


#include <create_map/create_map_srvRequest.h>
#include <create_map/create_map_srvResponse.h>


namespace create_map
{

struct create_map_srv
{

typedef create_map_srvRequest Request;
typedef create_map_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct create_map_srv
} // namespace create_map


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::create_map::create_map_srv > {
  static const char* value()
  {
    return "ce11d8a36ed22138f3ccd3ee60b5ca4a";
  }

  static const char* value(const ::create_map::create_map_srv&) { return value(); }
};

template<>
struct DataType< ::create_map::create_map_srv > {
  static const char* value()
  {
    return "create_map/create_map_srv";
  }

  static const char* value(const ::create_map::create_map_srv&) { return value(); }
};


// service_traits::MD5Sum< ::create_map::create_map_srvRequest> should match 
// service_traits::MD5Sum< ::create_map::create_map_srv > 
template<>
struct MD5Sum< ::create_map::create_map_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::create_map::create_map_srv >::value();
  }
  static const char* value(const ::create_map::create_map_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::create_map::create_map_srvRequest> should match 
// service_traits::DataType< ::create_map::create_map_srv > 
template<>
struct DataType< ::create_map::create_map_srvRequest>
{
  static const char* value()
  {
    return DataType< ::create_map::create_map_srv >::value();
  }
  static const char* value(const ::create_map::create_map_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::create_map::create_map_srvResponse> should match 
// service_traits::MD5Sum< ::create_map::create_map_srv > 
template<>
struct MD5Sum< ::create_map::create_map_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::create_map::create_map_srv >::value();
  }
  static const char* value(const ::create_map::create_map_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::create_map::create_map_srvResponse> should match 
// service_traits::DataType< ::create_map::create_map_srv > 
template<>
struct DataType< ::create_map::create_map_srvResponse>
{
  static const char* value()
  {
    return DataType< ::create_map::create_map_srv >::value();
  }
  static const char* value(const ::create_map::create_map_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CREATE_MAP_MESSAGE_CREATE_MAP_SRV_H
