// Generated by gencpp from file create_map/create_map_srvResponse.msg
// DO NOT EDIT!


#ifndef CREATE_MAP_MESSAGE_CREATE_MAP_SRVRESPONSE_H
#define CREATE_MAP_MESSAGE_CREATE_MAP_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace create_map
{
template <class ContainerAllocator>
struct create_map_srvResponse_
{
  typedef create_map_srvResponse_<ContainerAllocator> Type;

  create_map_srvResponse_()
    {
    }
  create_map_srvResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::create_map::create_map_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::create_map::create_map_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct create_map_srvResponse_

typedef ::create_map::create_map_srvResponse_<std::allocator<void> > create_map_srvResponse;

typedef boost::shared_ptr< ::create_map::create_map_srvResponse > create_map_srvResponsePtr;
typedef boost::shared_ptr< ::create_map::create_map_srvResponse const> create_map_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::create_map::create_map_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::create_map::create_map_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace create_map

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::create_map::create_map_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::create_map::create_map_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::create_map::create_map_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::create_map::create_map_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create_map::create_map_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create_map::create_map_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::create_map::create_map_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::create_map::create_map_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::create_map::create_map_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "create_map/create_map_srvResponse";
  }

  static const char* value(const ::create_map::create_map_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::create_map::create_map_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::create_map::create_map_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::create_map::create_map_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct create_map_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::create_map::create_map_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::create_map::create_map_srvResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CREATE_MAP_MESSAGE_CREATE_MAP_SRVRESPONSE_H
