// Generated by gencpp from file tiago_control/send_desired_poseRequest.msg
// DO NOT EDIT!


#ifndef TIAGO_CONTROL_MESSAGE_SEND_DESIRED_POSEREQUEST_H
#define TIAGO_CONTROL_MESSAGE_SEND_DESIRED_POSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tiago_control
{
template <class ContainerAllocator>
struct send_desired_poseRequest_
{
  typedef send_desired_poseRequest_<ContainerAllocator> Type;

  send_desired_poseRequest_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  send_desired_poseRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::tiago_control::send_desired_poseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiago_control::send_desired_poseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct send_desired_poseRequest_

typedef ::tiago_control::send_desired_poseRequest_<std::allocator<void> > send_desired_poseRequest;

typedef boost::shared_ptr< ::tiago_control::send_desired_poseRequest > send_desired_poseRequestPtr;
typedef boost::shared_ptr< ::tiago_control::send_desired_poseRequest const> send_desired_poseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiago_control::send_desired_poseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiago_control::send_desired_poseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tiago_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tiago_control': ['/home/phw/workspace/roboCupHome/src/tiago_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tiago_control::send_desired_poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiago_control::send_desired_poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiago_control::send_desired_poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiago_control::send_desired_poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago_control::send_desired_poseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago_control::send_desired_poseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiago_control::send_desired_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "938fa65709584ad8e77d238529be13b8";
  }

  static const char* value(const ::tiago_control::send_desired_poseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x938fa65709584ad8ULL;
  static const uint64_t static_value2 = 0xe77d238529be13b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::tiago_control::send_desired_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiago_control/send_desired_poseRequest";
  }

  static const char* value(const ::tiago_control::send_desired_poseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiago_control::send_desired_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::tiago_control::send_desired_poseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiago_control::send_desired_poseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct send_desired_poseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiago_control::send_desired_poseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiago_control::send_desired_poseRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIAGO_CONTROL_MESSAGE_SEND_DESIRED_POSEREQUEST_H
