(cl:defpackage simple_move-msg
  (:use )
  (:export
   "<SIMPLE_MOVEACTION>"
   "SIMPLE_MOVEACTION"
   "<SIMPLE_MOVEACTIONFEEDBACK>"
   "SIMPLE_MOVEACTIONFEEDBACK"
   "<SIMPLE_MOVEACTIONGOAL>"
   "SIMPLE_MOVEACTIONGOAL"
   "<SIMPLE_MOVEACTIONRESULT>"
   "SIMPLE_MOVEACTIONRESULT"
   "<SIMPLE_MOVEFEEDBACK>"
   "SIMPLE_MOVEFEEDBACK"
   "<SIMPLE_MOVEGOAL>"
   "SIMPLE_MOVEGOAL"
   "<SIMPLE_MOVERESULT>"
   "SIMPLE_MOVERESULT"
  ))

