; Auto-generated. Do not edit!


(cl:in-package simple_move-msg)


;//! \htmlinclude simple_moveGoal.msg.html

(cl:defclass <simple_moveGoal> (roslisp-msg-protocol:ros-message)
  ((goal_pose
    :reader goal_pose
    :initarg :goal_pose
    :type geometry_msgs-msg:Pose2D
    :initform (cl:make-instance 'geometry_msgs-msg:Pose2D)))
)

(cl:defclass simple_moveGoal (<simple_moveGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <simple_moveGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'simple_moveGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name simple_move-msg:<simple_moveGoal> is deprecated: use simple_move-msg:simple_moveGoal instead.")))

(cl:ensure-generic-function 'goal_pose-val :lambda-list '(m))
(cl:defmethod goal_pose-val ((m <simple_moveGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader simple_move-msg:goal_pose-val is deprecated.  Use simple_move-msg:goal_pose instead.")
  (goal_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <simple_moveGoal>) ostream)
  "Serializes a message object of type '<simple_moveGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <simple_moveGoal>) istream)
  "Deserializes a message object of type '<simple_moveGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<simple_moveGoal>)))
  "Returns string type for a message object of type '<simple_moveGoal>"
  "simple_move/simple_moveGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'simple_moveGoal)))
  "Returns string type for a message object of type 'simple_moveGoal"
  "simple_move/simple_moveGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<simple_moveGoal>)))
  "Returns md5sum for a message object of type '<simple_moveGoal>"
  "9c696f8357da6184167237a9d05c73bc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'simple_moveGoal)))
  "Returns md5sum for a message object of type 'simple_moveGoal"
  "9c696f8357da6184167237a9d05c73bc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<simple_moveGoal>)))
  "Returns full string definition for message of type '<simple_moveGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%geometry_msgs/Pose2D goal_pose  ~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'simple_moveGoal)))
  "Returns full string definition for message of type 'simple_moveGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%geometry_msgs/Pose2D goal_pose  ~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <simple_moveGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <simple_moveGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'simple_moveGoal
    (cl:cons ':goal_pose (goal_pose msg))
))
