; Auto-generated. Do not edit!


(cl:in-package simple_move-msg)


;//! \htmlinclude simple_moveActionGoal.msg.html

(cl:defclass <simple_moveActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type simple_move-msg:simple_moveGoal
    :initform (cl:make-instance 'simple_move-msg:simple_moveGoal)))
)

(cl:defclass simple_moveActionGoal (<simple_moveActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <simple_moveActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'simple_moveActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name simple_move-msg:<simple_moveActionGoal> is deprecated: use simple_move-msg:simple_moveActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <simple_moveActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader simple_move-msg:header-val is deprecated.  Use simple_move-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <simple_moveActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader simple_move-msg:goal_id-val is deprecated.  Use simple_move-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <simple_moveActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader simple_move-msg:goal-val is deprecated.  Use simple_move-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <simple_moveActionGoal>) ostream)
  "Serializes a message object of type '<simple_moveActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <simple_moveActionGoal>) istream)
  "Deserializes a message object of type '<simple_moveActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<simple_moveActionGoal>)))
  "Returns string type for a message object of type '<simple_moveActionGoal>"
  "simple_move/simple_moveActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'simple_moveActionGoal)))
  "Returns string type for a message object of type 'simple_moveActionGoal"
  "simple_move/simple_moveActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<simple_moveActionGoal>)))
  "Returns md5sum for a message object of type '<simple_moveActionGoal>"
  "1eb5d3bf2cd9a6e492f28bf7e03e8da5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'simple_moveActionGoal)))
  "Returns md5sum for a message object of type 'simple_moveActionGoal"
  "1eb5d3bf2cd9a6e492f28bf7e03e8da5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<simple_moveActionGoal>)))
  "Returns full string definition for message of type '<simple_moveActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%simple_moveGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: simple_move/simple_moveGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%geometry_msgs/Pose2D goal_pose  ~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'simple_moveActionGoal)))
  "Returns full string definition for message of type 'simple_moveActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%simple_moveGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: simple_move/simple_moveGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%geometry_msgs/Pose2D goal_pose  ~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <simple_moveActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <simple_moveActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'simple_moveActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
