; Auto-generated. Do not edit!


(cl:in-package simple_move-msg)


;//! \htmlinclude simple_moveFeedback.msg.html

(cl:defclass <simple_moveFeedback> (roslisp-msg-protocol:ros-message)
  ((current_pose
    :reader current_pose
    :initarg :current_pose
    :type geometry_msgs-msg:Pose2D
    :initform (cl:make-instance 'geometry_msgs-msg:Pose2D)))
)

(cl:defclass simple_moveFeedback (<simple_moveFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <simple_moveFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'simple_moveFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name simple_move-msg:<simple_moveFeedback> is deprecated: use simple_move-msg:simple_moveFeedback instead.")))

(cl:ensure-generic-function 'current_pose-val :lambda-list '(m))
(cl:defmethod current_pose-val ((m <simple_moveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader simple_move-msg:current_pose-val is deprecated.  Use simple_move-msg:current_pose instead.")
  (current_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <simple_moveFeedback>) ostream)
  "Serializes a message object of type '<simple_moveFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'current_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <simple_moveFeedback>) istream)
  "Deserializes a message object of type '<simple_moveFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'current_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<simple_moveFeedback>)))
  "Returns string type for a message object of type '<simple_moveFeedback>"
  "simple_move/simple_moveFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'simple_moveFeedback)))
  "Returns string type for a message object of type 'simple_moveFeedback"
  "simple_move/simple_moveFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<simple_moveFeedback>)))
  "Returns md5sum for a message object of type '<simple_moveFeedback>"
  "2b0ea7b4c98a98c1c13d4294982a54b5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'simple_moveFeedback)))
  "Returns md5sum for a message object of type 'simple_moveFeedback"
  "2b0ea7b4c98a98c1c13d4294982a54b5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<simple_moveFeedback>)))
  "Returns full string definition for message of type '<simple_moveFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%geometry_msgs/Pose2D current_pose~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'simple_moveFeedback)))
  "Returns full string definition for message of type 'simple_moveFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%geometry_msgs/Pose2D current_pose~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <simple_moveFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'current_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <simple_moveFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'simple_moveFeedback
    (cl:cons ':current_pose (current_pose msg))
))
