; Auto-generated. Do not edit!


(cl:in-package simple_move-msg)


;//! \htmlinclude simple_moveResult.msg.html

(cl:defclass <simple_moveResult> (roslisp-msg-protocol:ros-message)
  ((final_pose
    :reader final_pose
    :initarg :final_pose
    :type geometry_msgs-msg:Pose2D
    :initform (cl:make-instance 'geometry_msgs-msg:Pose2D)))
)

(cl:defclass simple_moveResult (<simple_moveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <simple_moveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'simple_moveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name simple_move-msg:<simple_moveResult> is deprecated: use simple_move-msg:simple_moveResult instead.")))

(cl:ensure-generic-function 'final_pose-val :lambda-list '(m))
(cl:defmethod final_pose-val ((m <simple_moveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader simple_move-msg:final_pose-val is deprecated.  Use simple_move-msg:final_pose instead.")
  (final_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <simple_moveResult>) ostream)
  "Serializes a message object of type '<simple_moveResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'final_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <simple_moveResult>) istream)
  "Deserializes a message object of type '<simple_moveResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'final_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<simple_moveResult>)))
  "Returns string type for a message object of type '<simple_moveResult>"
  "simple_move/simple_moveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'simple_moveResult)))
  "Returns string type for a message object of type 'simple_moveResult"
  "simple_move/simple_moveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<simple_moveResult>)))
  "Returns md5sum for a message object of type '<simple_moveResult>"
  "9b03b05e2f5c62e96e4cec4715bf432f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'simple_moveResult)))
  "Returns md5sum for a message object of type 'simple_moveResult"
  "9b03b05e2f5c62e96e4cec4715bf432f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<simple_moveResult>)))
  "Returns full string definition for message of type '<simple_moveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%geometry_msgs/Pose2D final_pose~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'simple_moveResult)))
  "Returns full string definition for message of type 'simple_moveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%geometry_msgs/Pose2D final_pose~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <simple_moveResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'final_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <simple_moveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'simple_moveResult
    (cl:cons ':final_pose (final_pose msg))
))
